name:                Intcode-Tasks
version:             0.1.0.0
github:              "githubuser/Intcode-Tasks"
license:             BSD3
author:              "Luke Tyler"
maintainer:          "example@example.com"
copyright:           "2021 Luke Tyler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Intcode-Tasks#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - transformers
  - array
  - split

executables:
  Intcode-Tasks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Intcode-Tasks
    - monad-loops
    - containers

tests:
  Intcode-Tasks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Intcode-Tasks
